apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: devfile-sample-ovnv
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: devfile-sample-ovnv
    app.kubernetes.io/part-of: adambkaplan-website
  name: devfile-sample-ovnv
  namespace: adkaplan-tenant
spec:
  ports:
  - port: 3001
    targetPort: 3001
  selector:
    app.kubernetes.io/instance: devfile-sample-ovnv
status:
  loadBalancer: {}
