apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  name: devfile-sample-ovnv
  namespace: adkaplan-tenant
spec:
  replicas: 1
  selector: {}
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
    spec:
      containers:
      - image: quay.io/redhat-appstudio/user-workload@sha256:2f66fb9d1681b81656ad06c906c8d6693021ed433562a7d0fe33927067b72002
        name: my-nodejs
        resources: {}
status: {}
